name: Package Repository with Submodules

on:
  release:
    types:
      - published
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
      with:
        submodules: true

    - name: Update Submodules
      run: git submodule update --init --recursive

    - name: Get Tag Name
      id: get_tag
      run: echo "TAG_NAME=$(git describe --tags --abbrev=0)" >> $GITHUB_ENV

    - name: Create ZIP Archive
      run: |
        tag_name="${{ env.TAG_NAME }}"
        mkdir "$tag_name"
        cp -r * "$tag_name"
        zip -r "$tag_name.zip" "$tag_name"

    - name: Upload ZIP Archive
      uses: actions/upload-artifact@v2
      with:
        name: repo_with_submodules
        path: ${{ steps.get_tag.outputs.tag }}.zip
