name: Package Repository with Submodules

on:
  push:
    tags:        
      - '*'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
      with:
        submodules: true

    - name: Update Submodules
      run: git submodule update --init --recursive

    - name: Get Tag Name
      id: get_tag
      run: echo "TAG_NAME=$(git describe --tags --abbrev=0)" >> $GITHUB_ENV

    - name: Create ZIP Archive
      run: |
        tag_name="${{ env.TAG_NAME }}"
        mkdir "comfyui-prompt-reader-node"
        rsync -av --exclude='.github' --exclude="comfyui-prompt-reader-node" * comfyui-prompt-reader-node
        zip -r "${tag_name}.zip" "comfyui-prompt-reader-node"

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        files: ${{ env.TAG_NAME }}.zip
